marcosdosea/RestauranteAki

- Analise de projeto/RestauranteAki.mdj
> Corrigidos diagramas de colaborações issue 44

- AnaliseProjeto/RestauranteAki.mdj
Foi efetuada a correção de acordo com descrição na issue.
> Corrigido do nome do package Persistence. Close #55

- AnaliseProjeto/RestauranteAki.mdj
> Refatorei Atributos do "DER" tabelas Pedido, Personagem, itemPedido, cardapio 

- AnaliseProjeto/RestauranteAki.mdj
> Criado os diagramas de Pacotes. Representacao os módulos principais o sistema (Boundary, Control, Entity, Persistence). 

- AnaliseProjeto/RestauranteAki.mdj
> Corrigido o Relacionamento  e atributos nas entidades Personagem e Pedido. "DER"

- AnaliseProjeto/RestauranteAki.mdj
Mudanças realizada:
Antes:
Depois:
Por favor revisar.
> Atualizado modelo DER de acordo com o instruções. close #95

- AnaliseProjeto/RestauranteAki.mdj
> Adicionado uma representaçao do diagrama de exceção na seçao Design Model

- AnaliseProjeto/RestauranteAki.mdj
> Corrigido o diagrama de pacotes na seçao Design model(StarUML) seguindo a arquitetura do projeto. 

- Site/RestauranteAki/Core/Service/ICardapio.cs
- Site/RestauranteAki/Core/Service/IContum.cs
- Site/RestauranteAki/Core/Service/IGarcom.cs
- Site/RestauranteAki/Core/Service/IItemcardapio.cs
- Site/RestauranteAki/Core/Service/IMesa.cs
- Site/RestauranteAki/Core/Service/IPagamento.cs
- Site/RestauranteAki/Core/Service/IPedido.cs
- Site/RestauranteAki/Core/Service/IPedidoItemcardapio.cs
- Site/RestauranteAki/Core/Service/IPersonagem.cs
- Site/RestauranteAki/Core/Service/IPessoa.cs
- Site/RestauranteAki/Core/Service/IRestaurante.cs
- Site/RestauranteAki/Service/CardapioService.cs
- Site/RestauranteAki/Service/ContumService.cs
- Site/RestauranteAki/Service/GarcomService.cs
- Site/RestauranteAki/Service/ItemcardapioService.cs
- Site/RestauranteAki/Service/MesaService.cs
- Site/RestauranteAki/Service/PagamentoService.cs
- Site/RestauranteAki/Service/PedidoItemcardapioService.cs
- Site/RestauranteAki/Service/PedidoService.cs
- Site/RestauranteAki/Service/PersonagemService.cs
- Site/RestauranteAki/Service/PessoaService.cs
- Site/RestauranteAki/Service/RestauranteService.cs
Necessário voltar a versão anterior por conta que arquivos que não deferiam ter sido removidos foram removidos.
> Revert "Corrigido Service e suas interfaces, seguindo arquitetura prevista."

- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
- Site/RestauranteAki/Service/PessoaService.cs
- Site/RestauranteAki/Service/Service.csproj
> Implementei PessoaService para gerenciar operações de Pessoa e configurações do projeto. 

- Site/RestauranteAki/RestauranteAki.sln
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/HomeControllerTests.cs
- Site/RestauranteAki/RestauranteAkiWebTests/RestauranteAkiWebTests.csproj
- Site/RestauranteAki/Service/GarcomService.cs
- Site/RestauranteAki/ServiceTests/GarcomServiceTests.cs
- Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Projetos de teste criados e erros de compilação corrigidos. Revisar por favor.
> Criar projetos de teste. Close #154

- Site/RestauranteAki/RestauranteAkiWeb/Views/Home/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Home/Privacy.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/js/site.js
> Implementado os componentes e layout da view RestauranteAkiWeb #168 Resolve

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/GarcomController.cs
> Criado controller referente a Garçom. close #169

- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/Service/PedidoService.cs
Implementação service para manter pedido + add na classe program a impl do service. Favor revisar.
> Implementado service do pedido. Close #173

- Site/RestauranteAki/Service/PedidoItemcardapioService.cs
> Implementado PedidoitemcardapioService para gerenciar operações #179 Resolve

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/ItemcardapioController.cs
> Criado as operações da Controller relacionadas à entidade Itemcardapio dentro da aplicação. 

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/PedidoController.cs
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Delete.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Details.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Index.cshtml
Implementei o controller e as views básicas para CRUD relacionados ao pedido. Close #175
> Implementar Manter Pedido - Controller + Views

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/PedidoItemcardapioController.cs
Atenção essa precisa de mais atenção possível na hora de revisar!
> Implementada a Controller para Pedido Item Cardapio #181 Resolve

- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
- Site/RestauranteAki/Service/RestauranteService.cs
> Implementado as Views do restaurante e ajustado os icons do layout Close  #195

- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/PedidoControllerTests.cs
- Site/RestauranteAki/RestauranteAkiWebTests/RestauranteAkiWebTests.csproj
- Site/RestauranteAki/ServiceTests/PedidoServiceTests.cs
- Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Implementei os teste relacionados ao pedido no controller e service. Revisar por favor.
> Implementado os testes - Manter pedido. Close #196

- Site/RestauranteAki/Service/CardapioService.cs
> Implementado CardapioService para gerenciar operações do cardapio. 

- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/RestauranteControllerTests.cs
> Implementado o teste da Controller do Restaurante #208 Close

- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
Correção básica que a validação seja triggada. Revisar por favor.
> Corrigir validação para campos de manter pedido. Close #211

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/CardapioController.cs
- Site/RestauranteAki/ServiceTests/CardapioServiceTests.cs
- Site/RestauranteAki/ServiceTests/GarcomServiceTests.cs
> Implementado Teste para Service e Controller da entidade Cardapio. 

- Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
- Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
> Adicionado views e layout referente ao itemcardapio seguindo o padrão do projeto. 

- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Details.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
Realize correção e padronização do design system das views de pedido. Provavelmente algo do tipo será usado no restante das views. Favor revisar.
> Padronização de todas as views de Pedido. Close #241

- Site/RestauranteAki/Core/Cardapio.cs
- Site/RestauranteAki/Core/Contum.cs
- Site/RestauranteAki/Core/Itemcardapio.cs
- Site/RestauranteAki/Core/Pessoa.cs
- Site/RestauranteAki/Core/Restaurante.cs
- Site/RestauranteAki/Core/RestauranteAkiContext.cs
- Site/RestauranteAki/RestauranteAkiWeb/Controllers/RestauranteController.cs
- Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
- Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
> Ajustado a RestauranteController e inclusão das Views do Restaurante Close #219

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/MesaController1.cs
- Site/RestauranteAki/Service/MesaService.cs
Foi criada as operações de CRU na controller de acordo com a arquitetura.
> Criado as operações da Controller relacionadas à entidade Mesa dentro da aplicação.

- Site/RestauranteAki/Service/MesaService.cs
implementado as regras de negocio prevista no projeto:
-Criado a implementação MesaService no Service.
-Implementar métodos GetAll, Get, Add, Update, Delete.
> Implementado MesaService para gerenciar operações das mesas.

- Site/RestauranteAki/Core/Cardapio.cs
- Site/RestauranteAki/Core/Contum.cs
- Site/RestauranteAki/Core/Itemcardapio.cs
- Site/RestauranteAki/Core/Pessoa.cs
- Site/RestauranteAki/Core/Restaurante.cs
- Site/RestauranteAki/Core/RestauranteAkiContext.cs
- Site/RestauranteAki/RestauranteAkiWeb/Controllers/RestauranteController.cs
- Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
- Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Delete.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Details.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Edit.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
> Criada as Views para o Restaurante Close #251

- Site/RestauranteAki/RestauranteAkiWeb/Controllers/ContaController.cs
- Site/RestauranteAki/RestauranteAkiWeb/Models/ContumViewModel.cs
- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Delete.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Details.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Edit.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Index.cshtml
Implementei controller e views para serem usados no caso de uso Encerrar Conta. Favor revisar.
> Implementação controller + views da entidade Conta

- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/ContaControllerTests.cs
- Site/RestauranteAki/ServiceTests/ContaServiceTests.cs
> Adicionado testes de service e controller referentes a Conta. Close #238

- Site/RestauranteAki/Core/Service/IItemcardapioService.cs
- Site/RestauranteAki/RestauranteAkiWeb/Controllers/ItemcardapioController.cs
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/CardapioControllerTests.cs
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/ItemcardapioControllerTests.cs
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/PessoaControllerTests.cs
- Site/RestauranteAki/RestauranteAkiWebTests/Controllers/RestauranteControllerTests.cs
- Site/RestauranteAki/Service/ItemcardapioService.cs
- Site/RestauranteAki/ServiceTests/ItemcardapioServiceTests.cs
- Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Realizei algumas mudanças em classes de service e controller bem como nas classes de teste para retirar os erros de compilação. Depois serão realizadas melhorias e correções nos casos de teste em si. Favor revisar.
> Erros de compilação nos testes corrigidos

- Site/RestauranteAki/Core/Core.csproj
- Site/RestauranteAki/Core/RestauranteAkiContext.cs
- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
- Site/RestauranteAki/Service/Service.csproj
- Site/RestauranteAki/ServiceTests/ContaServiceTests.cs
Alteração nas versões de alguns pacotes para resolução de problemas de conflitos nos projetos. Favor revisar
> Resolvidos conflitos de versões + erros estranhos nos projetos de teste

- Site/RestauranteAki/Core/Core.csproj
- Site/RestauranteAki/Core/RestauranteAkiContext.cs
- Site/RestauranteAki/RestauranteAkiWeb/Program.cs
- Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
- Site/RestauranteAki/Service/Service.csproj
- Site/RestauranteAki/ServiceTests/ContaServiceTests.cs
Reverts marcosdosea/RestauranteAki#267
> Revert "Resolvidos conflitos de versões + erros estranhos nos projetos de teste"

- Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Details.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGarcom.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGestor.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
Correções básicas de css para posterior uso e padronização.
> Revisão básica de css para melhorias de desenvolvimento. Close #262

- Site/RestauranteAki/Core/Exceptions/CepServiceException.cs
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/Email.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/Index.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/TwoFactorAuthentication.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Controllers/RestauranteApiController.cs
- Site/RestauranteAki/RestauranteAkiWeb/Controllers/ViaCepService.cs
- Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/Create.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_BuscarCepModal.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/auth-styles.css
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/modalCep.css
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
- Site/RestauranteAki/RestauranteAkiWeb/wwwroot/js/modal-cep.js
> Ajusto o layout, estilização do botão do CEP Close #305
